spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  配置静态资源访问前缀
#  mvc:
#    static-path-pattern: /resources/**
#    配置静态资源访问路径
#  web:
#    resources:
#      static-locations: classpath:/haha/
